config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'
  resources :departments do
    resources :items
  end
  resources :items do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  before_save :check_author
  belongs_to :item

  def check_author
    if self.author.blank?
      self.author = 'anon'
    end
  end
  
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item
  def new
    @comment = Comment.new
  end

  def create
    @comment = @item.comments.new(comment_params)
    if @comment.save
      redirect_to department_item_path(@item.department_id, @item)
    else
      render :new
    end
  end

  private
    def set_item
      @item = Item.find(params[:item_id])
    end
    def comment_params
      params.require(:comment).permit(:body, :author, :rating)
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  
  before_action :set_dep, only: [:show, :update, :edit, :destroy]

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def create
    @department = Department.new(dep_params)

    if @department.save
      redirect_to departments_path
    else
      render :new
    end

  end

  def update
    if @department.update(dep_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private
    def dep_params
      params.require(:department).permit(:name)
    end

    def set_dep
      @department = Department.find(params[:id])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_dep
  before_action :set_item, only: [:show, :update, :edit, :destroy]

  def index
    @items = @department.items
  end

  def show 
  end

  def new
    @item = @department.items.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def create
    @item = @department.items.new(item_params)

    if @item.save
      redirect_to department_items_path(@department)
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to [@department, @item]
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path
  end

  private
    def set_dep
      @department = Department.find(params[:department_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<hr>
<p>Author: <%= comment.author%> </p>
<p>Rating: <%= comment.rating%> </p>
<p><strong> <%=comment.body%> </strong></p>
<hr>

app/views/comments/new.html.erb
<h1>Add A comment</h1>
<%= form_for [@item, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Leave Blank To Remain Anonymous' %>
  <br />
  <%= f.label :rating%>
  <%= f.number_field :rating, min: 1, max: 5, step: 0.1 %>
  <%= f.submit %>
<% end %>

app/views/departments/_form.html.erb
<h1><%= @department.id ? 'Edit Department' : 'Create Department' %></h1>
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>
<%= link_to 'Back to Index', departments_path %>

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<h1>Welcome to the Department Store </h1>
<% @departments.each do |dep|%>
    <div class="department">
        <h2><%= link_to dep.name, department_path(dep) %></h2>
        <%= link_to 'Edit Department', edit_department_path(dep) %>
        <%= link_to 'Remove Department', department_path(dep), method: :delete %>
    </div>
<%end%>
<%= link_to 'Add a department', new_department_path, id: "add" %>

app/views/departments/show.html.erb
<h1> <%=@department.name%> </h1>
<%= link_to 'View items', department_items_path(@department) %>
<%= link_to 'Back to Index', departments_path %>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Add Item' %></h1>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />

  <%= f.label :price%>
  <%= f.number_field :price, :step => 0.01 %>

  <%= f.label :description %>
  <%= f.text_area :description %>
  
  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1>Click a Item to View More Info</h1>
<%= link_to 'Add an item', new_department_item_path(@department) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, [@department, item] %></li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1> <%=@department.name%>:<%= @item.name %> - $<%= @item.price %></h1>
<p><%= @item.description %></p>
<h2>Comments</h2>

<% @item.comments.each do |comment|%>
    <%= render 'comments/comment', { comment: comment } %>
<% end %>

<%= link_to 'Add Comment', new_item_comment_path(@item) %>
<%= link_to 'Edit item', edit_department_item_path([@department, @item]) %>
<%= link_to 'Remove item', [@department, @item], method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Montserrat:400,700' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>